version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer_db
    ports:
      - 3306:3306
    networks:
      - network
    volumes:
      - data-volume_bloc:/var/lib/mysql

  app-foyer:
    depends_on:
      - mysqldb
    image: lou4y/tp-foyer-bloc:latest
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    ports:
      - 8082:8082
    networks:
      - network
    stdin_open: true
    tty: true

  frontend:
    image: localhost:5000/bloc-frontend-dev:latest
    environment:
      - API_URL=http://localhost:8082/tpfoyer/bloc
    ports:
      - 4200:4200
    networks:
      - network
    depends_on:
      - app-foyer

volumes:
  data-volume_bloc:

networks:
  network:
    driver: bridge
